#!/bin/sh

start()
{
  su jenkins -c "nohup java -jar /opt/jenkins/bin/jenkins.war &"
}

stop()
{
  su jenkins -c "kill `ps -ef | grep [j]enkins.war | awk '{ print $2 }'`"
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
restart)
        stop
        start
        ;;
*)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

